config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: "dashboard#index"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_admin_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_admin_session
  end

  namespace :upload do
    get :new
    post :create
  end

  namespace :report do
    get '/show/:id', action: :show
  end

  get 'home/index'

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  has_many :report_item
end

app/models/report/item.rb
class Report::Item < ApplicationRecord
  belongs_to :report
end

app/models/user.rb
class User < ApplicationRecord
  has_many :report

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(
      email: data['email'],
      password: Devise.friendly_token[0, 20]
    ) if user.nil?

    user
  end

  def short_name
    self.email.first(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @reports = user_reports
    @reports_to_list = user_reports.page(params[:page]).per(5)
  end

  private

  def user_reports
    @user_reports ||= Report.where(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  before_action :authenticate_user!

  def show
    @report = Report.find_by(id: params[:id], user_id: current_user.id)
    @items = Report::Item.where(report_id: @report.id)
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    begin
      file_content = nil
      result = 0.0

      (1..10).each do |uploader_id|
        params_key = "upload_#{uploader_id}".to_sym
        next if params[params_key].nil?
        result += create_data_for_file(params[params_key])
      end

      redirect_to '/dashboard', notice: "Report successfully added<br/>Total gross income added: #{result}"
    rescue
      redirect_to '/upload/new', notice: "An error occurred while adding the report."
    end
  end

  private

  def create_data_for_file(file_data)
    if file_data.respond_to?(:read)
      file_content = file_data.read
    elsif file_data.respond_to?(:path)
      file_content = File.read(file_data.path)
    else
      logger.error "Bad file_data: #{file_data.class.name}: #{file_data.inspect}"
    end

    formatted_content = UploadFormatter.new(file_content).format
     Report::Create.new(current_user.id, formatted_content).now
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/dashboard/index.html.erb
<div class="row dashboard">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				Reports
			</div>
			<div class="card-body">

				<div class="card-group">
					<div class="card" style="width: 18rem;">
					  <div class="card-body">
					    <h5 class="card-title">Reports Count</h5>
					    <p id="reports-count" class="card-text"><%= Report.where(user_id: current_user.id).count %></p>
					  </div>
					</div>

					<div class="card" style="width: 18rem;">
					  <div class="card-body">
					    <h5 class="card-title">All-time gross income</h5>
					    <p id="all-time-gross-income" class="card-text"><%= @reports.sum(:total_price) %></p>
					  </div>
					</div>

					<div class="card" style="width: 18rem;">
					  <div class="card-body">
					    <h5 class="card-title">All-time purchased items</h5>
					    <p id="all-time-purchased-items" class="card-text"><%= @reports.sum(:purchase_count) %></p>
					  </div>
					</div>
				</div>
			</div>
		</div>

		<div class="card mt-3">
			<div class="card-header">
				Gross income by day
			</div>
			<div class="card-body">
				<%= line_chart @reports.group_by_day(:created_at).sum(:total_price) %>
			</div>
		</div>

		<div class="card mt-3 mb-3">
			<div class="card-header">
				Reports
			</div>
			<div class="card-body">

				<table class="table table-striped">
				  <thead class="table-dark">
				    <tr>
				      <th scope="col">#</th>
				      <th scope="col">Name</th>
				      <th scope="col">Purchase Count</th>
				      <th scope="col">Total Price</th>
				      <th scope="col">Actions</th>
				    </tr>
				  </thead>
				  <tbody>
				  	<% @reports_to_list.order(id: :DESC).each do |report| %>
					    <tr>
					      <th scope="row"><%= report.id %></th>
					      <td>Report_<%= report.created_at.to_s.gsub(' UTC', '') %></td>
					      <td><%= report.purchase_count %></td>
					      <td><%= report.total_price %></td>
					      <td>
					      	<a href="/report/show/<%= report.id %>">
					      		<i class="fa-solid fa-eye"></i>
				      		</a>
					      </td>
					    </tr>
				   	<% end %>
				  </tbody>
				</table>

				<div class="d-flex justify-content-center">
					<%= paginate @reports_to_list %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-body">
				<h1>Welcome</h1>
				<p>Hello, this is a Web Test project developed for Nuuvem.</p>
				<p>The project is a revenue manager and all data is entered manually via TAB-separated file upload.</p>
				<p>With each upload a new report is created and the lines from your file are added as Report Items.</p>
				<p>On the Dashboard page you will be able to follow the statistics, the gross income graph and a list with all the reports that have been inserted.</p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_alerts.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |key, value| %>
      <section class="alert alert-success <%= key %>"><%= value.html_safe %></section>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Nuuvem Test</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= render partial: "layouts/navbar/item",
        	locals: {
        		page_name: 'Home',
        		page_path: '/'
        	}
        %>

        <% unless current_user.present? %>
	        <%= render partial: "layouts/navbar/item",
	        	locals: {
	        		page_name: 'Sign in',
	        		page_path: '/users/sign_in'
	        	}
	        %>
        <% else %>
        	<%= render partial: "layouts/navbar/item",
	        	locals: {
	        		page_name: 'Upload',
	        		page_path: '/upload/new'
	        	}
	        %>

	        <%= render partial: "layouts/navbar/item",
	        	locals: {
	        		page_name: 'Dashboard',
	        		page_path: '/dashboard'
	        	}
	        %>
	      </ul>
      
	      <div class="navbar-shortname">
	      	<%= current_user.short_name.capitalize %>
	      </div>

	      <a
	      	href="/users/sign_out"
	      	class="logout-icon"
	      	data-bs-toggle="tooltip"
	      	data-bs-placement="bottom"
	      	title="Sair"
	      >
	      	<i class="fa-solid fa-right-from-bracket"></i>
	      </a>
			<% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nuuvem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container pt-5">
      <% if flash.any? %>
        <%= render "layouts/alerts" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/navbar/_item.html.erb
<li class="nav-item">
  <a class="nav-link <%= request.path.eql?(page_path) ? 'active' : '' %>" href="<%= page_path %>">
    <%= page_name %>
  </a>
</li>

app/views/report/show.html.erb
<div class="row">
	<div class="col-md-12">
		<a href="/dashboard" class="btn btn-secondary btn-sm">Back</a>
		<div class="card mt-2">
			<div class="card-header">
				Report_<%= @report.created_at.to_s.gsub(' UTC', '') %> (ID: <%= @report.id %>)
			</div>
			<div class="card-body">
				<table class="table table-striped">
					<thead class="table-dark">
						<tr>
							<th scope="col">Purchaser Name</th>
							<th scope="col">Item Description</th>
							<th scope="col">Item Price</th>
							<th scope="col">Purchase Count</th>
							<th scope="col">Merchante Address</th>
							<th scope="col">Merchant Name</th>
						</tr>
					</thead>
					<tbody>
						<% @items.each do |item| %>
							<tr>
								<td><%= item.purchaser_name %></td>
								<td><%= item.item_description %></td>
								<td><%= item.item_price %></td>
								<td><%= item.purchase_count %></td>
								<td><%= item.merchant_address %></td>
								<td><%= item.merchant_name %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/upload/new.html.erb
<div class="row mb-3">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				Upload
			</div>
			<div class="card-body">
				<%= form_tag upload_create_path, multipart: true do %>
					<div id="upload-fields" class="form-itens">
						<div class="upload-item">
					  	1. <%= file_field_tag :upload_1, required: true %>
					  </div>
					</div>
				  <div class="mt-3">
				  	<%= submit_tag "Upload", id: 'upload', class: 'btn btn-success btn-sm' %>
				  	<a id="add-upload-field" class="btn btn-secondary btn-sm" onclick="AddUploadField()">Add + file</a>
				  </div>
				<% end %>
			</div>
		</div>
	</div>
</div>

<%= javascript_include_tag "upload", "data-turbo-track": "reload", defer: true %>